[build-system]
requires = ["setuptools >= 61.0", "wheel >= 0.29.0"]
build-backend = "setuptools.build_meta"

[project]
name = "anyldap"
dynamic = ["version", "readme"]
description = "A Pure-Python AnyIO library for LDAP"
authors = [{ name = "Tommi Virtanen", email = "tv@eagain.net" }]
maintainers = [{ name = "Bret Curtis", email = "psi29a@gmail.com" }]
license = { text = "MIT" }
requires-python = ">=3.10"
dependencies = ["anyio", "dnspython", "passlib", "pyparsing", "zope.interface"]
classifiers = [
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 5 - Production/Stable",
    "Framework :: AsyncIO",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: System :: Systems Administration :: Authentication/Directory :: LDAP",
]
urls = { Homepage = "https://github.com/graingert/anyldap" }

[project.optional-dependencies]
docs = [
    "alabaster~=0.7.16; python_version == '3.10'",
    "alabaster~=1.0; python_version >= '3.11'",
    "commonmark~=0.9.1",
    "docutils~=0.21",
    "pillow~=12.0",
    "readthedocs-sphinx-ext~=2.2",
    "recommonmark~=0.7.1",
    "sphinx~=7.4; python_version == '3.10'",
    "sphinx~=8.2; python_version >= '3.11'",
    "sphinx-rtd-theme~=3.0",
]

[project.scripts]
anyldap-ldap2dhcpconf = "anyldap._scripts.ldap2dhcpconf:console_script"
anyldap-ldap2maradns = "anyldap._scripts.ldap2maradns:console_script"
anyldap-ldap2dnszones = "anyldap._scripts.ldap2dnszones:console_script"
anyldap-search = "anyldap._scripts.search:console_script"
anyldap-namingcontexts = "anyldap._scripts.namingcontexts:console_script"
anyldap-passwd = "anyldap._scripts.passwd:console_script"
anyldap-ldap2passwd = "anyldap._scripts.ldap2passwd:console_script"
anyldap-getfreenumber = "anyldap._scripts.getfreenumber:console_script"
anyldap-ldap2pdns = "anyldap._scripts.ldap2pdns:console_script"
anyldap-find-server = "anyldap._scripts.find_server:console_script"
anyldap-rename = "anyldap._scripts.rename:console_script"
anyldap-fetchschema = "anyldap._scripts.fetchschema:console_script"
anyldap-ldifdiff = "anyldap._scripts.ldifdiff:console_script"
anyldap-ldifpatch = "anyldap._scripts.ldifpatch:console_script"

[tool.setuptools]
include-package-data = true

[tool.setuptools.dynamic]
version = { attr = "anyldap.__version__" }
readme = { file = ["README.rst"], content-type = "text/x-rst" }

[tool.setuptools.packages.find]
include = ["anyldap*"]

[tool.coverage.run]
branch = true
source_pkgs = ["anyldap"]
parallel = true
patch = ["subprocess"]

[tool.coverage.report]
fail_under = 100
show_missing = true

[tool.coverage.paths]
source = [
    "anyldap",
    "*/site-packages/anyldap",
    '*\site-packages\anyldap',
]

[tool.pytest.ini_options]
addopts = "-ra --cov=anyldap --cov-report=term-missing --cov-fail-under=100"
testpaths = ["anyldap/test"]

[tool.ruff]
line-length = 368

[tool.ruff.lint]
select = ["E", "F", "W", "I"]
ignore = [
    "E101",
    "E203",
    "E265",
    "E401",
    "E402",
    "E713",
    "E741",
    "E743",
    "W191",
    "W291",
]


[tool.tox]
legacy_tox_ini = """
; tox configuration file for running tests on local dev env and CI.

[tox]
minversion=3.20.0
isolated_build=true
requires=
    virtualenv >= 20.1.0
;
; Tags explanation:
; * dev - run things in local dev mode
envlist =
    py{310,311,312,313,314,py3}-test
    py312-test-dev
    py312-linters,
    documentation,


[testenv]
parallel_show_output = True
deps = 
    anyio
    dnspython
    pyparsing
    pytest
    pytest-cov
    trustme
    trio
    passlib
    ; Dependecies for local dev environment.
    dev: diff_cover
    ; Linters are installed both on local dev and the dedicated env.
    {dev,linters}: pre-commit

; All environment variables are passed.
passenv = *

; Each command should have an associated tag as we use the same config for
; all the environments.
; This is done in order to reuse
commands =
    {envpython} --version
    test: pytest --version
    test: pytest {posargs:anyldap/test}

    ; Only run on local dev env.
    dev: coverage report --show-missing
    dev: coverage xml -o {toxinidir}/build/coverage.xml
    dev: coverage html -d build/coverage-html
    dev: diff-cover --fail-under 100 --html-report {toxinidir}/build/coverage-diff.html {toxinidir}/build/coverage.xml
    dev: pre-commit run --all-files --show-diff-on-failure
    linters: pre-commit {posargs:run --all-files --show-diff-on-failure}

[testenv:documentation]
deps = sphinx
basepython=python3.12
changedir = {envtmpdir}
allowlist_externals = cp
commands =
    sphinx-build -b html -Ean -j 2 -w sphinx-errors \
        {toxinidir}/docs/source ./docs/
    cp -r . {toxinidir}/build

[testenv:release]
deps = build
allowlist_externals =
    rm
commands =
    rm -rf {toxinidir}/dist
    {envpython} -m build --sdist --wheel --outdir {toxinidir}/dist {toxinidir}

[testenv:publishcov]
passenv = GITHUB_*
deps =
  codecov
  coverage[toml]>=5.3
commands =
    codecov --required
depends = py{310,311,312,313,314,py3}-test
"""

[tool.zest-releaser]
python-file-with-version = "anyldap/__init__.py"
history-file = "docs/source/NEWS.rst"
tag-format = "v{version}"
